/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <string.h>
#include "stm32f411x.h"
#include "stm32f411x_gpio.h"
#include "stm32f411x_timers.h"
#include "stm32f411x_usart.h"
int main(void)
{

	/*

	*					Configuring GPIO for SPI alt function 5
	===================================================================================================
	*/


	RCC_GPIOA_EN();
	RCC_USART2_EN();
	// Enable FPU
	uint32_t* FPU  = CPACR;
	*FPU |= (0xF<<20);
	USARTx_Handle_t Serial2;
	Serial2.pUSART = USART2;
	Serial2.USARTConfig.USART_Baudrate = 115200;
	Serial2.USARTConfig.USART_Hardware_Control = USART_CONTROL_NONE;
	Serial2.USARTConfig.USART_Mode = USART_MODE_ONLY_TX;
	Serial2.USARTConfig.USART_Parity  = USART_PARITY_NONE;
	Serial2.USARTConfig.USART_Stop_Bits = USART_STOP_1;
	Serial2.USARTConfig.USART_Word_length = USART_WORD_8bit;

	USART_Init(&Serial2);
	GPIOx_Handle_t LED;
	LED.pGPIOx = GPIOA;
	LED.GPIO_PinConfig.pinNumber = 2;
	LED.GPIO_PinConfig.pinAltFun = 7;
	LED.GPIO_PinConfig.pinMode = GPIO_MODE_OUT;
	LED.GPIO_PinConfig.pinOType = GPIO_OUTPUT_PP;
	LED.GPIO_PinConfig.pinPuPd = GPIO_PULL_NONE;
	LED.GPIO_PinConfig.pinSpeed = GPIO_SPEED_HIGH;


	GPIO_Init(&LED);



	char buffor[10] = "Hello";
	while (1)
	{
		//SPI_Send_Polling(SPI2,(uint8_t*)userData,strlen(userData));

		USART_Send_Polling(&Serial2,(uint8_t*)buffor,strlen(buffor));

	}



}
